name: Sample Docker Image CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
  #Allow to manually run the pipeline under Actions tab.
  workflow_dispatch:

jobs:
    
  build-job:
    env:
      IMAGE_NAME: mydockerimageName
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag ${{env.IMAGE_NAME}}:$(date +%s)
