name: Sample Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    
  build-job:
    env:
      IMAGE_NAME: mydockerimageName
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag ${{env.IMAGE_NAME}}:$(date +%s)
